### ISSUE TITLE
Lucene tests fail with java.lang.AssertionError and other exceptions

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal-core#140]
Get the Lucene source:

http://archive.apache.org/dist/lucene/java/5.5.0/lucene-5.5.0-src.tgz

and run the core tests:
```
cthaling@macbook:~/lucene-5.5.0/core$ ant test -Dtests.jvms=1
```
These runs are with JDK 9 because of #139.  The failures also reproduce with multiple JVMs but using one should make it more predictable.

The first test that fails for me is:
```
   [junit4] Suite: org.apache.lucene.search.TestNumericRangeQuery64
   [junit4]   2> NOTE: reproduce with: ant test  -Dtestcase=TestNumericRangeQuery64 -Dtests.method=testRandomTrieAndClassicRangeQuery_4bit -Dtests.seed=52DB7312B37CD6CD -Dtests.slow=true -Dtests.locale=mgh -Dtests.timezone=America/Jamaica -Dtests.asserts=true -Dtests.file.encoding=UTF-8
   [junit4] FAILURE 0.03s | TestNumericRangeQuery64.testRandomTrieAndClassicRangeQuery_4bit <<<
   [junit4]    > Throwable #1: java.lang.AssertionError: Out of order : 42 42
   [junit4]    > 	at __randomizedtesting.SeedInfo.seed([52DB7312B37CD6CD:ECF25C6EFB42FB8F]:0)
   [junit4]    > 	at org.apache.lucene.search.AssertingLeafCollector.collect(AssertingLeafCollector.java:48)
   [junit4]    > 	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:196)
```
After that we fail others a well (just to list a few):
```
   [junit4] Suite: org.apache.lucene.codecs.lucene53.TestLucene53NormsFormat
   [junit4]   2> NOTE: reproduce with: ant test  -Dtestcase=TestLucene53NormsFormat -Dtests.method=testOutliers -Dtests.seed=52DB7312B37CD6CD -Dtests.slow=true -Dtests.locale=en -Dtests.timezone=America/Catamarca -Dtests.asserts=true -Dtests.file.encoding=UTF-8
   [junit4] FAILURE 0.28s | TestLucene53NormsFormat.testOutliers <<<
   [junit4]    > Throwable #1: java.lang.AssertionError: 85
```
```
   [junit4] Suite: org.apache.lucene.codecs.lucene54.TestLucene54DocValuesFormat
   [junit4]   2> NOTE: reproduce with: ant test  -Dtestcase=TestLucene54DocValuesFormat -Dtests.method=testZeroOrMin -Dtests.seed=52DB7312B37CD6CD -Dtests.slow=true -Dtests.locale=id-ID -Dtests.timezone=Europe/Vienna -Dtests.asserts=true -Dtests.file.encoding=UTF-8
   [junit4] FAILURE 0.07s | TestLucene54DocValuesFormat.testZeroOrMin <<<
   [junit4]    > Throwable #1: java.lang.AssertionError: backwards nextDoc from 58 to 58 org.apache.lucene.codecs.lucene50.Lucene50PostingsReader$BlockDocsEnum@1b2da3a3
```

**Comment by tkrodriguez** [comment]
I've only been able to reliably reproduce the AFTER_EXCEPTION_BCI problem with any reliability.  The problem is that we have an AFTER_EXCEPTION_BCI state on a monitor exit which contains a virtualiizable object and we're trying to rematerialize it.  We've rematerialized it before frame state assignment and the state which uses it goes away during FSA but the FixedValueAnchor that uses the allocation stays around.

I think AFTER_EXCEPTION_BCI states should be empty.  There's no possible way their frame states could be used for deopt so the values they reference aren't useful.  They are actually the source of the problem here.  Forcibly clearing the locals of the state for this bci seems to fix this problem, though it's a little tricky to ensure that they are never set.  Maybe it should be done as part of FSA?  @gilles-duboscq

**Comment by gilles-duboscq** [comment]
We could clear the state in the graph builder if that helps not keeping useless things alive. However, does that not just hide 2 problems for this specific case?

1. Why did the rematerialization end up in a place where no valid state could ever be provided? Should we prevent pushing allocation past `MergeNodes` with a `FrameState` that has a `AFTER_EXCEPTION_BCI` (or any other kind of invalid bci)? Should we not create the merge point in the graph builder in first place?
2. Why can we not eliminate that useless allocation once the `FrameState` that was using it disappeared?

**Comment by tkrodriguez** [comment]
Yes there are other problems to be resolved here.  As far as the allocation it's kept alive by the ValueAnchor created during lowering.  I would expect this logic to remove the anchor though:

<pre>
        if (anchored != null && (anchored.isConstant() || anchored instanceof FixedNode)) {
            // anchoring fixed nodes and constants is useless
            removeAnchoredNode();
        }
</pre>

anchored is a NewInstanceNode.  I'll see if I can figure that out.  The allocation has initializing stores and I don't think we have anything that runs after FSA that would remove them.  Even a bare NewInstanceNode wouldn't be removed after FSA would it?  I wonder how much dead code like this we have after FSA?

Concerning the merges, I think AFTER_EXCEPTION_BCI is different than the others.  It represents a point where deoptimization isn't allowed to happen, so properly clearing out the state seems like it should cover most cases.  I guess the exception that we're unwinding with could be PEA'd and somehow end up below an AFTER_EXCEPTION_BCI merge.  It would probably be good to force materialization above any AFTER_EXCEPTION_BCI state.  Lukas, any suggestion where to put such a test in PEA?

**Comment by tkrodriguez** [comment]
I just realized this is a FixedValueAnchorNode which appears to be different than a ValueAnchorNode even though that's also a FixedNode.  FixedValueAnchorNode does no canonicalization.  Why does it exist and/or why is it used for lowering a CommitAllocationNode?

**Comment by tkrodriguez** [comment]
This problem doesn't appear to be uncommon.  Iterators used in loops with multiple exits that merge seem to sometimes end up materializing the iterator at the merge because the state uses it and then after FSA it's no longer used but we have no optimization capable of removing it.  It requires EA to get rid of it at this point or a targeted removal.  I wrote a simple piece of logic that detects a single allocation that is dead after FSA and got some dumps.  I've attached the dumps for several of them.  I'm a little surprised that method liveness doesn't eliminate these from the merge state but our liveness isn't precise at a per bytecode granularity so maybe that's the reason.

[graphs.zip](https://github.com/graalvm/graal-core/files/187128/graphs.zip)

**Comment by tkrodriguez** [comment]
It looks like the cases I'm seeing are because we aren't using the liveness information when building the merge at the loop exits.  Fixing that should eliminate the dead allocations after FSA.

**Comment by tkrodriguez** [comment]
The AFTER_EXCEPTION_BCI issue was resolved by https://github.com/graalvm/graal-core/commit/d1cf16c.  I'll check whether other issues still exist.

**Comment by tkrodriguez** [comment]
There are still failure with lucene and the latest graalvm though they look different.  I'm also seeing different errors with graal-core and graalvm so there are probably bugs at several levels.  The graalvm ones seem to be problems with bit manipulations leaving an extra bit set.  I'm investigating.

**Comment by thomaswue** [comment]
@tkrodriguez Can you rerun on latest version to check if this is still an issue?
