### ISSUE TITLE
Truffle interop tests are failing when run with graal-core

### ISSUE THREAD

**Issue by dougxc** [graalvm/graal-core#15]
```
dsimon@kurz ~/g/graal-core> mx --vm server unittest ClassInteropTest#readCONST
MxJUnitCore
JUnit version 4.11
.E
Time: 0.111
There was 1 failure:
1) readCONST(com.oracle.truffle.api.interop.java.test.ClassInteropTest)
java.lang.RuntimeException: com.oracle.truffle.api.interop.UnknownIdentifierException: Unknown identifier: CONST
	at com.oracle.graal.truffle.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:225)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:82)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	at com.oracle.truffle.api.interop.CachedObjectAccessNode.doAccess(CachedObjectAccessNode.java:55)
	at com.oracle.truffle.api.interop.CachedObjectAccessNode.executeWith(CachedObjectAccessNode.java:50)
	at com.oracle.truffle.api.interop.UnresolvedObjectAccessNode.executeWith(UnresolvedObjectAccessNode.java:45)
	at com.oracle.truffle.api.interop.ForeignObjectAccessHeadNode.executeForeign(ForeignObjectAccessHeadNode.java:52)
	at com.oracle.truffle.api.interop.ForeignAccess.execute(ForeignAccess.java:98)
	at com.oracle.truffle.api.interop.java.JavaInterop$TemporaryRoot.execute(JavaInterop.java:514)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:442)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:325)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:311)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:299)
	at com.oracle.graal.truffle.OptimizedCallTarget.call(OptimizedCallTarget.java:204)
	at com.oracle.truffle.api.interop.java.JavaInterop.message(JavaInterop.java:489)
	at com.oracle.truffle.api.interop.java.JavaInterop$TruffleHandler.invoke(JavaInterop.java:397)
	at com.sun.proxy.$Proxy4.CONST(Unknown Source)
	at com.oracle.truffle.api.interop.java.test.ClassInteropTest.readCONST(ClassInteropTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.oracle.mxtool.junit.MxJUnitWrapper.main(MxJUnitWrapper.java:167)
Caused by: com.oracle.truffle.api.interop.UnknownIdentifierException: Unknown identifier: CONST
	at com.oracle.truffle.api.interop.UnknownIdentifierException.raise(UnknownIdentifierException.java:63)
	at com.oracle.truffle.api.interop.java.InvokeMemberNode.execute(InvokeMemberNode.java:60)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:442)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:325)
	at com.oracle.graal.truffle.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:311)
	at com.oracle.graal.truffle.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:299)
	at com.oracle.graal.truffle.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:211)
	... 39 more

FAILURES!!!
Tests run: 1,  Failures: 1
```

**Comment by jtulach** [comment]
Alas. I can't reproduce the failure. This is what I did:
```bash
graal-core$ mx --vm server build
graal-core$ mx --vm server unittest ClassInteropTest#readCONST
MxJUnitCore
JUnit version 4.11
.
Time: 0.172

OK (1 test)

graal-core$ git show
commit d8c144406f5d27aa82b00149c750891603e4d4b7
Merge: 5734cac 538a130
Author: Douglas Simon <doug.simon@oracle.com>
Date:   Wed Feb 10 20:35:53 2016 +0100

    Merge pull request #14 from zapster/resurrect-old-mx-gate
    
    Resurrect old mx gate and add --simple flag for travis
```

**Comment by dougxc** [comment]
@woess just tried to update the truffle import in graal-core but the gate [fails](https://travis-ci.org/graalvm/graal-core/builds/108611020) due to this error.

I investigated it a little and came up with the fix below. Not sure if it's the right fix though - @jtulach and  @grimmerm, what do you think?

```
diff --git a/graal/com.oracle.graal.truffle/src/com/oracle/graal/truffle/OptimizedCallTarget.java b/graal/com.oracle.graal.truffle/src/com/oracle/graal/truffle/OptimizedCallTarget.java
index bed5f04..da8acd4 100644
--- a/graal/com.oracle.graal.truffle/src/com/oracle/graal/truffle/OptimizedCallTarget.java
+++ b/graal/com.oracle.graal.truffle/src/com/oracle/graal/truffle/OptimizedCallTarget.java
@@ -64,6 +64,7 @@ import com.oracle.truffle.api.Truffle;
 import com.oracle.truffle.api.frame.FrameDescriptor;
 import com.oracle.truffle.api.frame.VirtualFrame;
 import com.oracle.truffle.api.impl.DefaultCompilerOptions;
+import com.oracle.truffle.api.interop.InteropException;
 import com.oracle.truffle.api.nodes.ExplodeLoop;
 import com.oracle.truffle.api.nodes.Node;
 import com.oracle.truffle.api.nodes.NodeUtil;
@@ -204,6 +205,11 @@ public class OptimizedCallTarget extends InstalledCode implements RootCallTarget
         return doInvoke(args);
     }

+    @SuppressWarnings({"unchecked", "unused"})
+    private static <E extends Exception> RuntimeException silenceException(Class<E> type, Exception ex) throws E {
+        throw (E) ex;
+    }
+
     public final Object callDirect(Object... args) {
         compilationProfile.reportDirectCall();
         profileArguments(args);
@@ -218,6 +224,8 @@ public class OptimizedCallTarget extends InstalledCode implements RootCallTarget
             t = exceptionProfile.profile(t);
             if (t instanceof RuntimeException) {
                 throw (RuntimeException) t;
+            } else if (t instanceof InteropException) {
+                throw silenceException(RuntimeException.class, (InteropException) t);
             } else if (t instanceof Error) {
                 throw (Error) t;
             } else {
```

**Comment by woess** [comment]
@dougxc Yes, it's the exception wrapping in OptimizedCallTarget.callDirect that's causing this because the interop throws (undeclared) checked exceptions. I've updated #19 with a (similar) fix. Let's see if it passes now.

**Comment by woess** [comment]
@jtulach @grimmerm I find this (ab)use of checked exceptions in the api.interop.* questionable.

**Comment by grimmerm** [comment]
@jtulach and I had a long discussion about that; @jtulach, can you recap the decision?

**Comment by jtulach** [comment]
Yes, it is questionable and deserves some explanation. I prepare one.

The thing that puzzles me is that the unit test worked OK on my computer. Why was that?

Btw. rather than having a direct dependency on InteropException, you can silently re-throw any java.lang.Exception. At least the code will be ready for future cases when Truffle throws checked exceptions silently.

**Comment by woess** [comment]
> The thing that puzzles me is that the unit test worked OK on my computer. Why was that?

You probably didn't run it with Graal (--jdk jvmci).

**Comment by jtulach** [comment]
I followed what I was told to do. Btw. Isn't it the default to run with just built JVM when running
```bash
graal-core$ mx --vm server unittest ClassInteropTest#readCONST
```
in graal-core repository? If it is not, then such behavior is highly unintuitive.

**Comment by dougxc** [comment]
@jtulach I assume you checked out a fresh clone of graal-core and it updated to the version of truffle it was currently target to. This means you weren't testing against the latest truffle bits.

Not sure I understand your question about "just built JVM". When running something with `--vm server` it will use the result of `--vm server build`.

**Comment by jtulach** [comment]
Right, I checked fresh clone of graal-core out. Now, when thinking about it, it was probably naive, but I couldn't imagine I got a bug report without exact steps to reproduce the problem.

**Comment by dougxc** [comment]
Sorry for the ambiguity - will ensure you get precise steps next time. I need to remember not everyone has a graal-core sibling directory of truffle ready at all times ;-)
