### ISSUE TITLE
java.lang.NullPointerException with -Dgraal.PrintCompilation=true

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal-core#203]
While looking at some compilation output I saw this fly by:

```
26840  JVMCI Lsun/management/counter/perf/PerfInstrumentation;                      findByPattern                                 (Ljava/lang/String;)Ljava/util/List;               (OSR@73) ...
java.lang.NullPointerException
	at com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:226)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:93)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:393)
```

This commit https://github.com/graalvm/graal-core/commit/b47ed04b19291e9ad42902ea6b00349f34a664a6 forgot to check for `result != null`.

**Comment by gilles-duboscq** [comment]
Fixed in 95501e72df6765e8acf9f003e6794f2396acd6c4
