### ISSUE TITLE
java/lang/invoke/BigArityTest.java fails with: com.oracle.graal.graph.VerificationError: Phase LoopUnswitching specifies to increase/decrease code size by a factor of 10.000000, but codesize.before(338.000000)* increaseFactor(10.000000) >/=/< codesize.after(3414.000000). Real factor is:10.100592 [Delta:0.338000]

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal-core#209]
Running JDK regression tests with `-XX:+EnableJVMCI -XX:+UseJVMCICompiler` shows some failures, like this one:

```
[thread:7] scope: JVMCI CompilerThread1
  [thread:7] scope: JVMCI CompilerThread1.HotSpotGraalCompiler
    [thread:7] scope: JVMCI CompilerThread1.HotSpotGraalCompiler.Compiling
      [thread:7] scope: JVMCI CompilerThread1.HotSpotGraalCompiler.Compiling.GraalCompiler
        [thread:7] scope: JVMCI CompilerThread1.HotSpotGraalCompiler.Compiling.GraalCompiler.FrontEnd
          [thread:7] scope: JVMCI CompilerThread1.HotSpotGraalCompiler.Compiling.GraalCompiler.FrontEnd.HighTier
            [thread:7] scope: JVMCI CompilerThread1.HotSpotGraalCompiler.Compiling.GraalCompiler.FrontEnd.HighTier.LoopUnswitchingPhase
              [thread:7] scope: JVMCI CompilerThread1.HotSpotGraalCompiler.Compiling.GraalCompiler.FrontEnd.HighTier.LoopUnswitchingPhase.InterceptException
              Exception occurred in scope: JVMCI CompilerThread1.HotSpotGraalCompiler.Compiling.GraalCompiler.FrontEnd.HighTier.LoopUnswitchingPhase.InterceptException
              Context obj com.oracle.graal.graph.VerificationError: Phase LoopUnswitching specifies to increase/decrease code size by a factor of 10.000000, but codesize.before(338.000000)* increaseFactor(10.000000) >/=/< codesize.after(3414.000000). Real factor is:10.100592 [Delta:0.338000] [Method:HotSpotMethod<MethodTypeForm.canonicalizeAll(Class[], int)>]
              Context obj com.oracle.graal.loop.phases.LoopUnswitchingPhase@57a104ce
              Context obj com.oracle.graal.compiler.phases.HighTier@5c95fe8c
              Context obj StructuredGraph:23145{HotSpotMethod<MethodTypeForm.canonicalizeAll(Class[], int)>}
              Context obj jdk.vm.ci.hotspot.HotSpotCodeCacheProvider@e98e499
              Context obj DebugDumpScope[39353]
              Context obj HotSpotMethod<MethodTypeForm.canonicalizeAll(Class[], int)>
com.oracle.graal.graph.VerificationError: Phase LoopUnswitching specifies to increase/decrease code size by a factor of 10.000000, but codesize.before(338.000000)* increaseFactor(10.000000) >/=/< codesize.after(3414.000000). Real factor is:10.100592 [Delta:0.338000] [Method:HotSpotMethod<MethodTypeForm.canonicalizeAll(Class[], int)>]
	at com.oracle.graal.phases.contract.NodeCostUtil.phaseAdheresSizeContract(NodeCostUtil.java:129)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:176)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:154)
	at com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:154)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:170)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:154)
	at com.oracle.graal.compiler.GraalCompiler.emitFrontEnd(GraalCompiler.java:202)
	at com.oracle.graal.compiler.GraalCompiler.compile(GraalCompiler.java:175)
	at com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:162)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:136)
	at com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:212)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:93)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:409)
```

**Comment by davleopo** [comment]
Thanks, this is a verification we run to ensure compilation does not explode code size.
However, it should only be enabled explicitly and currently it is done if assertions are enabled, this will be fixed soon.

**Comment by davleopo** [comment]
This should be fixed, phase size verification is no longer enabled per default if assertions are enabled.

**Comment by christhalinger** [comment]
Thanks.
