### ISSUE TITLE
java/lang/management/ThreadMXBean/ThreadLists.java fails with: java.lang.RuntimeException: inconsistent results

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal-core#210]
I wonder if this is related to the _external thread view_ we were discussing on the mailing list:

```
STDOUT:
ThreadGroup: 10 active thread(s)
Thread: 18 stack trace(s) returned
ThreadMXBean: 18 live threads(s)
ThreadMXBean: 18 thread Id(s)
STDERR:
java.lang.RuntimeException: inconsistent results
	at ThreadLists.main(ThreadLists.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:226)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dougxc** [comment]
How are you running this? On what JDK? That test passes for me on jdk9. In any case, this is a JVMCI or JDK issue and so please file a bug on the OpenJDK jira and close this issue.
