### ISSUE TITLE
Monitorenter doesn't work with -XX:-JVMCIUseFastLocking

### ISSUE THREAD

**Issue by theRealAph** [graalvm/graal-core#228]
The argument list is wrong.

```
Bootstrapping JVMCIjava.lang.ArrayIndexOutOfBoundsException: 3
	at com.oracle.graal.replacements.SnippetTemplate$Arguments.addConst(SnippetTemplate.java:345)
	at com.oracle.graal.replacements.SnippetTemplate$Arguments.addConst(SnippetTemplate.java:340)
	at com.oracle.graal.hotspot.replacements.MonitorSnippets$Templates.lower(MonitorSnippets.java:563)
	at com.oracle.graal.hotspot.meta.DefaultHotSpotLoweringProvider.lower(DefaultHotSpotLoweringProvider.java:289)
	at com.oracle.graal.hotspot.amd64.AMD64HotSpotLoweringProvider.lower(AMD64HotSpotLoweringProvider.java:72)
	at com.oracle.graal.nodes.java.RawMonitorEnterNode.lower(RawMonitorEnterNode.java:70)
	at com.oracle.graal.phases.common.LoweringPhase$Round.process(LoweringPhase.java:419)
	at com.oracle.graal.phases.common.LoweringPhase$Round.access$0(LoweringPhase.java:392)
	at com.oracle.graal.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:359)
	at com.oracle.graal.phases.common.LoweringPhase.processBlock(LoweringPhase.java:518)
	at com.oracle.graal.phases.common.LoweringPhase$Round.run(LoweringPhase.java:344)
	at com.oracle.graal.phases.Phase.run(Phase.java:51)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:166)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:148)
	at com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:154)
	at com.oracle.graal.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:54)
	at com.oracle.graal.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:1)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:166)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:148)
	at com.oracle.graal.phases.common.LoweringPhase.lower(LoweringPhase.java:252)
	at com.oracle.graal.phases.common.LoweringPhase.run(LoweringPhase.java:245)
	at com.oracle.graal.phases.common.LoweringPhase.run(LoweringPhase.java:1)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:166)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:148)
	at com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:154)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:166)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:148)
	at com.oracle.graal.compiler.GraalCompiler.emitFrontEnd(GraalCompiler.java:213)
	at com.oracle.graal.compiler.GraalCompiler.compile(GraalCompiler.java:178)
	at com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:164)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:170)
	at com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:236)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:124)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:429)
```

**Comment by dougxc** [comment]
Can anyone remember why we have `JVMCIUseFastLocking` instead of just using `UseFastLocking`? Oh, I see that the latter is actually a C1 specific flag.

**Comment by dougxc** [comment]
Fixed by https://github.com/graalvm/graal-core/commit/984ffd07f4d57b4e6cd30d8804b304f1daa17ed6
