### ISSUE TITLE
`no JVMCI compiler selected` when running graal-0.18 built from source

### ISSUE THREAD

**Issue by vext01** [graalvm/graal-core#239]
Hi,

Having built a graal-0.18 from source, I'm now trying to run it. As I understand it (from reading the README), the invocation should look like this:

```
/path/to/mx -p path/to/graal-jvmci-8 vm -XX:+UseJVMCICompiler \
    <classname> <program-args>
```

It the context of our benchmark runner, it's a bit more complicated. Concretely I am invoking the vm like this:

```
env JAVA_HOME=work/graal-jvmci-8/jdk1.8.0/product \
    CLASSPATH=/home/vext01/research/warmup_experiment/krun/iterations_runners:/home/vext01/research/warmup_experiment/benchmarks/spectralnorm/java LD_LIBRARY_PATH=/home/vext01/research/warmup_experiment/work/gcc-inst/lib64:/home/vext01/research/warmup_experiment/krun/krun/../libkrun \
    work/mx/mx -p work/graal-jvmci-8 vm -XX:+UseJVMCICompiler \
    IterationsRunner KrunEntry 10 3 1 0
```

The VM runs the program OK, but prints to stdout (a few times):

```
jdk.vm.ci.common.JVMCIError: no JVMCI compiler selected
        at jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig$DummyCompilerFactory.compileMethod(HotSpotJVMCICompilerConfig.java:45)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:429)
```

In the part I've used `-Mjit` instead of `-XX...`. This doesn't appear to help.

Am I missing something?

**Comment by vext01** [comment]
Ah! `-p work/graal-jvmci-8` should be `work/graal`. User error!
