### ISSUE TITLE
OOME from GraalVM 0.19 while using NetBeans 8.2 (on Kubuntu 14.04)

### ISSUE THREAD

**Issue by jonatan-kazmierczak** [graalvm/graal-core#246]
Some info which possibly can be useful.
I'm using NetBeans 8.2 on GraalVM package 0.19 (build 25.71-b01-internal-jvmci-0.23) on Kubuntu 14.04.
I'm using NB only as a Java source code editor. At some point, while changing tab, it was frozen for a while (over 30s) with CPU cores 100% utilized.
Then it started to work again. In the shell console there was the following info printed:
```
WatchDog19[JVMCI CompilerThread2] detected long running compilation (id=64576) of org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.doComputeHints(CompilationInfo, Map, Map, Map, Collection) [31.00 seconds]
        com.oracle.graal.graph.NodeBitMap$MarkedNodeIterator.forward(NodeBitMap.java:207)
        com.oracle.graal.graph.NodeBitMap$MarkedNodeIterator.next(NodeBitMap.java:220)
        com.oracle.graal.graph.NodeBitMap$MarkedNodeIterator.next(NodeBitMap.java:184)
        com.oracle.graal.graph.iterators.PredicatedProxyNodeIterator.forward(PredicatedProxyNodeIterator.java:42)
        com.oracle.graal.graph.iterators.NodeIterator.hasNext(NodeIterator.java:38)
        com.oracle.graal.loop.phases.LoopTransformations.findUnswitchable(LoopTransformations.java:142)
        com.oracle.graal.loop.phases.LoopUnswitchingPhase.run(LoopUnswitchingPhase.java:56)
        com.oracle.graal.loop.phases.ContextlessLoopPhase.run(ContextlessLoopPhase.java:47)
        com.oracle.graal.loop.phases.ContextlessLoopPhase.run(ContextlessLoopPhase.java:29)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:149)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:131)
        com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:154)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:149)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:131)
        com.oracle.graal.compiler.GraalCompiler.emitFrontEnd(GraalCompiler.java:205)
        com.oracle.graal.compiler.GraalCompiler.compile(GraalCompiler.java:178)
        com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:164)
        com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:173)
        com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:229)
        com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:127)
        jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:429)
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to /home/jonatan/.netbeans/8.2/var/log/heapdump.hprof ...
Heap dump file created [1230355504 bytes in 5.629 secs]
```

Mentioned `heapdump.hprof` is 1.2GB of size (compressed to 74MB) - can publish it somewhere upon request.

**Comment by dougxc** [comment]
I assume the 30s pause was for the generation of the `heapdump.hprof` file.

In the next GraalVM relase, the watchdog thread will be disabled by default so you will now see such OOMEs on an application thread. For now, this means you need to increase the memory required to run NetBeans (e.g., to 2g).
We are currently focusing on reducing the memory requirements of Graal in the context of faster warmup. This will go some of the way in terms of mitigating how much Graal reduces memory available for the application. However, to achieve complete isolation from the app heap will require GC tricks such as zone-allocating Graal objects. We have a project underway investigating this but it will still be a while before it shows up in a GraalVM release. Even then, it will initially only be for an SVM based GraalVM since doing it for HotSpot will require extensive changes to the HotSpot garbage collectors.

**Comment by dougxc** [comment]
It would still be interesting to look at the `heapdump.hprof` file. I'll email you a link to some cloud space where you can upload it.

**Comment by jonatan-kazmierczak** [comment]
Hi Douglas, thanks for your extensive comment!
I will publish heapdumps tomorrow - so they will be ready for 1.02.

In the meantime I had another OOME from GraalVM (using NetBeans).
This time I've collected also the GC log with `jstat -gc pid 5s`.
Please note the enormous delta in memory usage in 4th row (I didn't do any action in NB at that time):
+300MB EU (Eden/YoungGen usage) and +300MB OU (OldGen usage) = +600MB within 5s - it seems to be quite much.

```
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT   
....
55296.0 52224.0  0.0   45982.6 239616.0   0.0     526848.0   296648.5  276972.0 202770.2 35092.0 22222.8    637   11.513  16      7.859   19.372
59904.0 47104.0  0.0   47053.6 233472.0 60723.6   526848.0   297648.5  276972.0 202770.2 35092.0 22222.8    639   11.570  16      7.859   19.429
78336.0 75776.0 224.0   0.0   185856.0   0.0     526848.0   370211.2  276972.0 202770.2 35092.0 22222.8    658   11.972  16      7.859   19.831
26112.0 26112.0 26112.0  0.0   296960.0 296960.0  699392.0   699389.6  276972.0 198781.3 35092.0 21696.9    704   12.507  18      8.717   21.225
26112.0 26112.0  0.0    0.0   296960.0 296960.0  699392.0   699185.9  276972.0 198585.4 35092.0 21667.0    704   12.507  22     14.028   26.535
26112.0 26112.0  0.0    0.0   296960.0 296960.0  699392.0   699325.7  276972.0 198585.8 35092.0 21667.0    704   12.507  26     18.641   31.148
26112.0 26112.0  0.0    0.0   296960.0 296960.0  699392.0   699293.3  276972.0 198585.8 35092.0 21667.0    704   12.507  35     23.791   36.298
26112.0 26112.0  0.0    0.0   296960.0 296960.0  699392.0   699309.6  276972.0 198508.1 35092.0 21655.9    704   12.507  43     29.119   41.626
26112.0 26112.0  0.0    0.0   296960.0 296960.0  699392.0   699388.0  276972.0 198508.1 35092.0 21655.9    704   12.507  53     33.916   46.423
26112.0 26112.0  0.0    0.0   296960.0 296960.0  699392.0   699387.9  276972.0 198508.1 35092.0 21655.9    704   12.507  55     34.299   46.806
26112.0 26112.0  0.0    0.0   296960.0 296960.0  699392.0   699386.7  276972.0 198508.1 35092.0 21655.9    704   12.507  65     39.793   52.300
26112.0 26112.0  0.0    0.0   296960.0 296960.0  699392.0   699390.7  276972.0 198508.1 35092.0 21655.9    704   12.507  74     44.560   57.068
26112.0 26112.0  0.0    0.0   296960.0 157655.6  699392.0   312419.2  276972.0 198508.1 35092.0 21655.9    704   12.507  78     47.102   59.610
26112.0 26112.0  0.0    0.0   296960.0 157680.5  699392.0   312419.2  276972.0 198508.1 35092.0 21655.9    704   12.507  78     47.102   59.610
```

And the stacktrace from WatchDog (which, I think, is very useful; otherwise how would I know that OOME is caused by GraalVM?):
```
WatchDog13[JVMCI CompilerThread0] detected long running compilation (id=61947) of org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.doComputeHints(CompilationInfo, Map, Map, Map, Collection) [31.00 seconds]
        com.oracle.graal.graph.GraphNodeIterator.forward(GraphNodeIterator.java:49)
        com.oracle.graal.graph.GraphNodeIterator.next(GraphNodeIterator.java:70)
        com.oracle.graal.graph.GraphNodeIterator.next(GraphNodeIterator.java:30)
        com.oracle.graal.graph.NodeBitMap$MarkedNodeIterator.forward(NodeBitMap.java:202)
        com.oracle.graal.graph.NodeBitMap$MarkedNodeIterator.next(NodeBitMap.java:220)
        com.oracle.graal.graph.NodeBitMap$MarkedNodeIterator.next(NodeBitMap.java:184)
        com.oracle.graal.enterprise.e.c$c.Q(stripped:568)
        com.oracle.graal.enterprise.e.c$c.a(stripped:398)
        com.oracle.graal.enterprise.e.c$c.a(stripped:359)
        com.oracle.graal.enterprise.e.c.a(stripped:133)
        com.oracle.graal.enterprise.e.g.run(stripped:711)
        com.oracle.graal.enterprise.e.g.run(stripped:86)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:149)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:131)
        com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:154)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:149)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:131)
        com.oracle.graal.compiler.GraalCompiler.emitFrontEnd(GraalCompiler.java:205)
        com.oracle.graal.compiler.GraalCompiler.compile(GraalCompiler.java:178)
        com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:164)
        com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:173)
        com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:229)
        com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:127)
        jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:429)
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /home/jonatan/.netbeans/8.2/var/log/heapdump.hprof ...
Heap dump file created [1216554127 bytes in 5.779 secs]
WatchDog13[JVMCI CompilerThread0] encountered an exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.Thread.dumpThreads(Native Method)
        at java.lang.Thread.getStackTrace(Thread.java:1546)
        at com.oracle.graal.hotspot.CompilationWatchDog.run(CompilationWatchDog.java:223)
```

**Comment by dougxc** [comment]
If you find the WatchDog useful, then you will need to enable it explicitly as of GraalVM 0.20 (as we do in our testing to catch these kind of errors).

It will be interesting to see what percentage of objects in your heap dumps are Graal objects. As stated earlier, there are unavoidable heap requirements for Graal. Do you still get the OOME when you give NetBeans 2G of memory?

**Comment by jonatan-kazmierczak** [comment]
Hi Douglas,
Now I'm working on 2GB heap and the problem with heap consumption and NetBeans freezing occurred again, although without OOME.

Please see GC log from `jstat -gc pid 5s`:
```
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT   
...
81408.0 94720.0 81395.2  0.0   509440.0 283716.7  466432.0   378554.3  256984.0 210383.8 32768.0 23173.2    300    6.652   9      2.785    9.437
94720.0 94720.0  0.0   94695.3 509440.0 153223.3  466432.0   385260.4  256984.0 210410.9 32768.0 23173.2    301    6.701   9      2.785    9.486
109056.0 112640.0  0.0   544.0  456704.0   0.0     536064.0   381132.0  256984.0 200092.4 32768.0 21742.2    317    7.142  10      3.399   10.541
157184.0 157184.0  0.0   157184.0 384512.0   0.0     898048.0   865966.9  256984.0 200103.1 32768.0 21742.8    335    7.614  12      4.216   11.829
157184.0 232960.0 118778.0  0.0   232960.0 15311.7  1398272.0  1267341.1  256984.0 200103.1 32768.0 21742.8    336    7.873  13      6.844   14.716
157184.0 232960.0 118778.0  0.0   232960.0 15650.5  1398272.0  1267341.1  256984.0 200103.1 32768.0 21742.8    336    7.873  13      6.844   14.716
157184.0 232960.0 118778.0  0.0   232960.0 25310.6  1398272.0  1267341.1  256984.0 200103.1 32768.0 21742.8    336    7.873  13      6.844   14.716
157184.0 232960.0 118778.0  0.0   232960.0 45518.2  1398272.0  1267341.1  256984.0 200103.1 32768.0 21742.8    336    7.873  13      6.844   14.716
157184.0 232960.0 118778.0  0.0   232960.0 101157.7 1398272.0  1267341.1  256984.0 200103.1 32768.0 21742.8    336    7.873  13      6.844   14.716
157184.0 232960.0 118778.0  0.0   232960.0 232960.0 1398272.0  1267341.1  256984.0 200103.1 32768.0 21742.8    336    7.873  14      6.844   14.716
232960.0 232960.0  0.0    0.0   232960.0 73600.4  1398272.0  1332650.6  256984.0 200183.2 32768.0 21746.6    341    8.241  18     11.013   19.254
232960.0 232960.0  0.0    0.0   232960.0  8301.0  1269760.0   388382.8  256984.0 200194.5 32768.0 21746.6    341    8.241  20     12.130   20.371
232960.0 232960.0  0.0    0.0   232960.0 10061.9  1269760.0   388382.8  256984.0 200194.5 32768.0 21746.6    341    8.241  20     12.130   20.371
```
You can see, that within 45s heap usage changed: 372M -> 1.3G -> 379M.

And the corresponding info from WatchDog:
```
WatchDog14[JVMCI CompilerThread0] detected long running compilation (id=60090) of org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.doComputeHints(CompilationInfo, Map, Map, Map, Collection) [31.00 seconds]
        com.oracle.graal.graph.GraphNodeIterator.forward(GraphNodeIterator.java:49)
        com.oracle.graal.graph.GraphNodeIterator.next(GraphNodeIterator.java:70)
        com.oracle.graal.graph.GraphNodeIterator.next(GraphNodeIterator.java:30)
        com.oracle.graal.graph.NodeBitMap$MarkedNodeIterator.forward(NodeBitMap.java:202)
        com.oracle.graal.graph.NodeBitMap$MarkedNodeIterator.next(NodeBitMap.java:220)
        com.oracle.graal.graph.NodeBitMap$MarkedNodeIterator.next(NodeBitMap.java:184)
        com.oracle.graal.graph.iterators.PredicatedProxyNodeIterator.forward(PredicatedProxyNodeIterator.java:42)
        com.oracle.graal.graph.iterators.NodeIterator.hasNext(NodeIterator.java:38)
        com.oracle.graal.loop.phases.LoopTransformations.findUnswitchable(LoopTransformations.java:142)
        com.oracle.graal.loop.phases.LoopUnswitchingPhase.run(LoopUnswitchingPhase.java:56)
        com.oracle.graal.loop.phases.ContextlessLoopPhase.run(ContextlessLoopPhase.java:47)
        com.oracle.graal.loop.phases.ContextlessLoopPhase.run(ContextlessLoopPhase.java:29)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:149)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:131)
        com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:154)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:149)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:131)
        com.oracle.graal.compiler.GraalCompiler.emitFrontEnd(GraalCompiler.java:205)
        com.oracle.graal.compiler.GraalCompiler.compile(GraalCompiler.java:178)
        com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:164)
        com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:173)
        com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:229)
        com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:127)
        jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:429)
```

Does Graal have an option to switch on some detailed logging which I could pass as well?

**Comment by dougxc** [comment]
Nothing that will help much with a compiler phase that is doing too much allocation. @davleopo , can you think of anything?

In any case, please wait until GraalVM 0.20 is released (shortly) and see if some of the efforts we've made in memory consumption and misbehaving phases mitigate this issue.

**Comment by jonatan-kazmierczak** [comment]
I've published 2 heap dumps corresponding to 2 reported OOMEs:
- http://class-visualizer.net/graalvm/heapdump_170127.hprof.xz
- http://class-visualizer.net/graalvm/heapdump_170130.hprof.xz

**Comment by christianhaeubl** [comment]
- heap dump 170127: the JVMCI CompilerThread2 is responsible for 72% of the memory usage. 85% of those 72% are objects that were allocated during SSA linear scan register allocation (long[] arrays that are part of the BitSets used in LinearScan$BlockData).
- heap dump 170130 shows the same issue (with only slightly different percentages).

**Comment by jonatan-kazmierczak** [comment]
@christianhaeubl (with delay) Thanks very much for your valuable analysis! Which tool did you use for that?

**Comment by christianhaeubl** [comment]
@jonatan-kazmierczak: Eclipse Memory Analyzer

**Comment by jonatan-kazmierczak** [comment]
Finally - OOME even with 2GB of heap.

Result of `jstat -gc 6904 5s` - please note the growth of heap usage from 700M to over 1.8G within 15s (starting from row 4):
```
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT   
138240.0 109568.0  0.0   109424.3 441856.0 201703.9  576512.0   378410.5  214336.0 171959.4 27752.0 18941.9    289    6.550  10      3.398    9.948
138240.0 109568.0  0.0   109424.3 441856.0 369109.2  576512.0   378410.5  214336.0 171959.4 27752.0 18941.9    289    6.550  10      3.398    9.948
51712.0 53248.0  0.0   16293.3 576512.0 132580.6  576512.0   525916.0  214336.0 175074.8 27752.0 19349.9    327    7.284  10      3.398   10.681
9216.0 8704.0 192.0   0.0   678400.0 310998.9  572928.0   379182.6  214336.0 172103.1 27752.0 18943.0    362    7.612  12      4.785   12.396
25088.0 16896.0  0.0    0.0   652800.0 34935.7   617472.0   373775.0  214336.0 172133.9 27752.0 18938.1    389    7.995  14      5.907   13.902
49664.0 232960.0 49644.5  0.0   232960.0   0.0    1181696.0  1180370.3  214336.0 172177.9 27752.0 18940.2    392    8.411  16      7.075   15.486
49664.0 232960.0 9043.3  0.0   232960.0 232960.0 1398272.0  1398223.0  214336.0 172091.4 27752.0 18923.6    392    8.411  20     13.409   21.820
49664.0 232960.0 9043.3  0.0   232960.0 232960.0 1398272.0  1398205.2  214336.0 172087.6 27752.0 18923.0    392    8.411  26     18.352   26.763
49664.0 232960.0 2381.0  0.0   232960.0 232960.0 1398272.0  1398134.7  214336.0 171786.0 27752.0 18879.6    392    8.411  33     23.315   31.725
49664.0 232960.0 2381.0  0.0   232960.0 232960.0 1398272.0  1398263.3  214336.0 171782.2 27752.0 18879.0    392    8.411  40     27.995   36.406
49664.0 232960.0 2381.0  0.0   232960.0 232960.0 1398272.0  1398263.3  214336.0 171782.2 27752.0 18879.0    392    8.411  40     27.995   36.406
49664.0 232960.0 2381.0  0.0   232960.0 232960.0 1398272.0  1398261.3  214336.0 171782.2 27752.0 18879.0    392    8.411  46     30.904   39.314
49664.0 232960.0 2381.0  0.0   232960.0 232960.0 1398272.0  1398088.7  214336.0 171782.2 27752.0 18879.0    392    8.411  54     36.578   44.989
49664.0 232960.0 2381.0  0.0   232960.0 232960.0 1398272.0  1398247.1  214336.0 171782.2 27752.0 18879.0    392    8.411  62     41.783   50.194
49664.0 232960.0 2381.0  0.0   232960.0 232960.0 1398272.0  1398266.1  214336.0 171783.8 27752.0 18879.0    392    8.411  72     46.695   55.105
```

And WatchDog info:
```
WatchDog13[JVMCI CompilerThread0] detected long running compilation (id=52346) of org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.doComputeHints(CompilationInfo, Map, Map, Map, Collection) [31.00 seconds]
        com.oracle.graal.nodes.cfg.ControlFlowGraph.computeLoopBlocks(ControlFlowGraph.java:464)
        com.oracle.graal.nodes.cfg.ControlFlowGraph.computeLoopInformation(ControlFlowGraph.java:370)
        com.oracle.graal.nodes.cfg.ControlFlowGraph.compute(ControlFlowGraph.java:74)
        com.oracle.graal.phases.schedule.SchedulePhase$Instance.run(SchedulePhase.java:142)
        com.oracle.graal.phases.schedule.SchedulePhase.run(SchedulePhase.java:126)
        com.oracle.graal.phases.Phase.run(Phase.java:47)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:149)
        com.oracle.graal.phases.Phase.apply(Phase.java:40)
        com.oracle.graal.virtual.phases.ea.EffectsPhase.runAnalysis(EffectsPhase.java:87)
        com.oracle.graal.virtual.phases.ea.PartialEscapePhase.run(PartialEscapePhase.java:80)
        com.oracle.graal.virtual.phases.ea.PartialEscapePhase.run(PartialEscapePhase.java:42)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:149)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:131)
        com.oracle.graal.enterprise.k.d.run(stripped:127)
        com.oracle.graal.enterprise.k.d.run(stripped:52)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:149)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:131)
        com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:154)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:149)
        com.oracle.graal.phases.BasePhase.apply(BasePhase.java:131)
        com.oracle.graal.compiler.GraalCompiler.emitFrontEnd(GraalCompiler.java:205)
        com.oracle.graal.compiler.GraalCompiler.compile(GraalCompiler.java:178)
        com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:164)
        com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:173)
        com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:229)
        com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:127)
        jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:429)
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /home/jonatan/.netbeans/8.2/var/log/heapdump.hprof ...
Heap dump file created [1924970930 bytes in 7.602 secs]
```

I will expose `heapdump.hprof` for tomorrow.

BTW, how can I switch on WatchDog on GraalVM 0.20 ?

**Comment by dougxc** [comment]
Snipping output from `/Library/Java/JavaVirtualMachines/graalvm-0.20/bin/java -XX:+JVMCIPrintProperties`:
```
graal.CompilationWatchDogStackTraceInterval = 60.0                        [Double]
          Interval in seconds between a watch dog reporting stack traces for long
          running compilations.
graal.CompilationWatchDogStartDelay = 0.0                                 [Double]
          Delay in seconds before watch dog monitoring a compilation (0 disables
          monitoring).
```
So, adding `-DCompilationWatchDogStartDelay=10` will enable observation of compilations lasting 10 seconds or longer.

**Comment by jonatan-kazmierczak** [comment]
Thanks very much for all these useful options; `-XX:+JVMCIPrintProperties` will become my favourite one :)

I'd interpret the option as `-Dgraal.CompilationWatchDogStartDelay=X` - thanks for additional explanation of its usage.

**Comment by jonatan-kazmierczak** [comment]
Today's heap dump (1.8G): http://class-visualizer.net/graalvm/heapdump_170316.hprof.xz

BTW, I see that GraalVM 0.21 is released - have to try that one now :)
