### ISSUE TITLE
Build failure on Debian8: missing `server' JVM

### ISSUE THREAD

**Issue by vext01** [graalvm/graal-core#270]
Hi,

I'm trying to update the Graal version in an automated build script for a research project.

My setup:

* The machine is Debian8/amd64
* The bootstrap JDK version is `jdk8u121-b13` (to match the OTN version a the time of writing)
* The JVMCI version is `jvmci-0.25` (newest git tag in jvmci repo)
* The graal version is `graal-vm-0.22` (newest git tag in graal-core repo)

I've successfully built (I think) the JVMCI enabled JDK8, now the graal-core stage is failing. The failing command is:

```
env PATH=/home/vext01/warmup_experiment/work/gcc-inst/bin:${PATH} \
    python2.7 /home/vext01/warmup_experiment/work/mx/mx.py \
    --java-home /home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8.0_121/product
```

Which gives:

```
Path in --java-home' is not pointing to a JDK (4: Error: missing `server' JVM at `/home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8
.0_121/product/jre/lib/amd64/server/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
)
Please select a default JDK: 
[1] Java 1.8.0_111 (1.8) from /usr/lib/jvm/java-8-openjdk-amd64
[2] Java 1.7.0_111 (1.7) from /usr/lib/jvm/java-7-openjdk-amd64
[3] <other>
Enter number of selection:
```

The argument I am passing to `--java-home` came from `mx jdkhome`, as suggested in the docs.

Looks like the jvmci build didn't install a libjvm.so?
```
$ ls /home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8.0_121/product/jre/lib/amd64/server/libjvm.so
ls: cannot access /home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8.0_121/product/jre/lib/amd64/server/libjvm.so: No such file or directory
```

Seems the whole server directory is missing in fact:
```
$ ls /home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8.0_121/product/jre/lib/amd64/server
ls: cannot access /home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8.0_121/product/jre/lib/amd64/server: No such file or directory
```

I can confirm that the bootstrap JDK did have a server library directory:
```
$ ls work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/jdk/lib/amd64/server/
libjsig.so  libjvm.so  Xusage.txt
```

When building the JVMCI JVM, I used:
```
--java-home /home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/
```

I've also tried (at the JVMCI build stage):
```
--java-home /home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/jdk
```

This gives a different error message when building graal-core:
```
The VM does not support the minimum JVMCI API version required by Graal.
Cannot read JVMCI version from java.vm.version property: 25.121-b13.
Set the JVMCI_VERSION_CHECK environment variable to "ignore" to suppress this error or to "warn" to emit a warning and continue execution.
```

Which perhaps suggests that the version string is wrong. When building the bootstrap JVM i passed to configure:
```
./configure \
    ...
    --with-update-version=121 \                                                                                      
    --with-build-number=b13 \
    ...
```

(As shown here: http://www.linuxfromscratch.org/blfs/view/svn/general/openjdk.html)

The exact sequence of commands used are here:
https://github.com/softdevteam/warmup_experiment/blob/update-vms-2017/build.sh#L480

Note that we deviate a little from the documented build commands in the README, as for our experiment it is essential we used fixed versions of dependencies.

Any help would be most appreciated. Thanks

**Comment by dougxc** [comment]
Does `/home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jvm.cfg` exist? If so, what's in it?

Could you post the complete output of `mx -v --java-home /home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/ build` here.

**Comment by vext01** [comment]
Hi Doug,

```
$ less /home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jvm.cfg
/home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jvm.cfg: No such file or directory
```

I'll get the build log now, but note that the `--java-home` path you suggested I use is not the same as is returned by `mx jdkhome`.

`mx jdkhome` says `/home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8.0_121/product`

**Comment by vext01** [comment]
I assume we are talking about the graal-core build step, not the JVMCI build step here?

**Comment by dougxc** [comment]
No, I'm talking about the JVMCI build step as it is obviously not producing a working JDK. Until we solve that, there's little point in looking at graal. The fact that the boot JDK doesn't have a `jvm.cfg` is almost certainly the problem although why you're not hitting the [check](http://hg.openjdk.java.net/graal/graal-jvmci-8/file/0e0a4ebf09d7/mx.jvmci/mx_jvmci.py#l522) for this is confusing.
I assume `mx unittest` in the graal-jvmci-8 repo after `mx build` fails as well.

**Comment by vext01** [comment]
Ah. I was missing a `|| exit $?` in my build script, so i was missing an earlier failure. My apologies.

The real failure appears to be an mx error:
```
+ [ ! -d /home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8.0 ]
+ env PATH=/home/vext01/warmup_experiment/work/gcc-inst/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games python2.7 /home/vext01/warmup_experiment/work/mx/mx.py --java-home /home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/ sforceimports
+ env PATH=/home/vext01/warmup_experiment/work/gcc-inst/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games python2.7 /home/vext01/warmup_experiment/work/mx/mx.py --java-home /home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/ build
Creating /home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8.0_121/product from /home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image
Compiling com.oracle.mxtool.compilerserver with javac... [/home/vext01/warmup_experiment/work/mx/mxbuild/java/com.oracle.mxtool.compilerserver/bin/com/oracle/mxtool/compilerserver/CompilerDaemon.class does not exist]
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
Traceback (most recent call last):
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 15308, in <module>
    main()
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 15292, in main
    retcode = c(command_args)
  File "/home/vext01/warmup_experiment/work/graal-jvmci-8/mx.jvmci/mx_jvmci.py", line 1043, in build
    mx.build(['--source', '1.7'] + args, parser=parser)
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 10153, in build
    task.prepare(daemons)
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 2333, in prepare
    self.compiler.prepare_daemon(self.jdk, daemons, self.compileArgs)
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 2688, in prepare_daemon
    self.daemon = JavacDaemon(jdk, jvmArgs)
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 2791, in __init__
    CompilerDaemon.__init__(self, jdk, jvmArgs, 'com.oracle.mxtool.compilerserver.JavacDaemon', jdk.toolsjar, ['--force-javac'])
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 2744, in __init__
```

**Comment by vext01** [comment]
Maybe my mx is too new? It's the version as of yesterday, not the mx of jvmci-0.25.

**Comment by dougxc** [comment]
Can you please add `-v` to your build command.

**Comment by vext01** [comment]
Ah yeah, my apologies.

With `mx -v build`, the output of the `build_graal` section of my build script looks like this:

```
===> Download and build graal

Cloning into 'mx'...
Note: checking out '720976e8c52527416f7aec95262c9a47d93602c4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 720976e... [GR-3685] Update overlay version.
*** Bootstrap JDK8 version:
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
destination directory: graal-jvmci-8
requesting all changes
adding changesets
adding manifests
adding file changes
added 24132 changesets with 129934 changes to 19040 files
updating to branch default
5030 files updated, 0 files merged, 0 files removed, 0 files unresolved
21 files updated, 0 files merged, 0 files removed, 0 files unresolved
[project jdk.vm.ci.hotspot.jfr was removed as dependency JFR is missing]
[jdk.vm.ci.hotspot.jfr was removed from distribution JVMCI_HOTSPOT]
Creating /home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8.0_121/product from /home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image
Create/update SHA1 cache file /home/vext01/warmup_experiment/work/graal-jvmci-8/mxbuild/intel/hsdis-amd64-linux-0d031013db9a80d6c88330c42c983fbfa7053193.so.sha1
Updating /home/vext01/warmup_experiment/work/graal-jvmci-8/jdk1.8.0_121/product/release
Starting daemon for /home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java [-d64]
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
Cleaning /home/vext01/warmup_experiment/work/mx/mxbuild/java/com.oracle.mxtool.compilerserver/bin...
Compiling com.oracle.mxtool.compilerserver with javac... [/home/vext01/warmup_experiment/work/mx/mxbuild/java/com.oracle.mxtool.compilerserver/bin/com/oracle/mxtool/compilerserver/CompilerDaemon.class does not exist]
/home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/javac -J-d64 -g -classpath '' -d /home/vext01/warmup_experiment/work/mx/mxbuild/java/com.oracle.mxtool.compilerserver/bin -proc:none -source 1.7 -target 1.7 @/home/vext01/warmup_experiment/work/mx/mxbuild/java/com.oracle.mxtool.compilerserver/javafilelist.txt -Xlint:all,-auxiliaryclass,-processing -XDignore.symbol.file -encoding UTF-8
Finished Compiling com.oracle.mxtool.compilerserver with javac
/home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java -d64 -cp /home/vext01/warmup_experiment/work/mx/mxbuild/java/com.oracle.mxtool.compilerserver/bin:/home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image/lib/tools.jar com.oracle.mxtool.compilerserver.JavacDaemon -v -j 4
Started server on port 56032 [4 threads]
[Error starting javac-daemon on port 56032 for Java 1.8.0_121 (1.8) from /home/vext01/warmup_experiment/work/jdk8u121-b13_fullsource/build/linux-x86_64-normal-server-release/images/j2sdk-image: [Errno 110] Connection timed out]
Traceback (most recent call last):
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 15308, in <module>
    main()
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 15292, in main
    retcode = c(command_args)
  File "/home/vext01/warmup_experiment/work/graal-jvmci-8/mx.jvmci/mx_jvmci.py", line 1043, in build
    mx.build(['--source', '1.7'] + args, parser=parser)
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 10153, in build
    task.prepare(daemons)
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 2333, in prepare
    self.compiler.prepare_daemon(self.jdk, daemons, self.compileArgs)
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 2688, in prepare_daemon
    self.daemon = JavacDaemon(jdk, jvmArgs)
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 2791, in __init__
    CompilerDaemon.__init__(self, jdk, jvmArgs, 'com.oracle.mxtool.compilerserver.JavacDaemon', jdk.toolsjar, ['--force-javac'])
  File "/home/vext01/warmup_experiment/work/mx/mx.py", line 2744, in __init__
    raise e
socket.error: [Errno 110] Connection timed out
```

And I also know what's wrong. I'd been running dacapo with some very strict firewall settings, even blocking loopback. By adding:

```
-A INPUT -i lo -j ACCEPT
```

to the iptables rules, graal now builds.

Sorry for the noise.

**Comment by dougxc** [comment]
Glad to hear you could solve this. Always run `mx unittest` in your JVMCI repo after (believing!) you have successfully build the VM binary.
