### ISSUE TITLE
Compilation Failure with AssertionError on IntegerStamp Creation

### ISSUE THREAD

**Issue by smarr** [graalvm/graal-core#271]
After updating to https://github.com/graalvm/graal-core/commit/11ec1deb54c9b2aa2c3ded338e4115ca7b15e120, I am seeing compilation problems that manifest as assertion failures on creating integer stamps.

It looks roughly like this, full stacktrace in details:
```
java.lang.AssertionError
	at org.graalvm.compiler.core.common.type.IntegerStamp.createStamp(IntegerStamp.java:316)
	at org.graalvm.compiler.core.common.type.IntegerStamp.meet(IntegerStamp.java:334)
	at org.graalvm.compiler.nodes.type.StampTool.meetOrNull(StampTool.java:66)
	at org.graalvm.compiler.nodes.ValuePhiNode.inferStamp(ValuePhiNode.java:71)
```

<details>

```
Starting CD benchmark ... 
[thread:21] scope: TruffleCompilerThread-21
  [thread:21] scope: TruffleCompilerThread-21.Truffle
  Context: Truffle<Method_RedBlackTree>>#treeAt:insert:	@14f01e19()>
    [thread:21] scope: TruffleCompilerThread-21.Truffle.TruffleGraal.GraalCompiler
    Context: StructuredGraph:4{Method RedBlackTree>>#treeAt:insert:	@14f01e19, HotSpotMethod<OptimizedCallTarget.callRoot(Object[])>}
        [thread:21] scope: TruffleCompilerThread-21.Truffle.TruffleGraal.GraalCompiler.GraalCompilerRoot.GraalCompiler
        Context: StructuredGraph:4{Method RedBlackTree>>#treeAt:insert:	@14f01e19, HotSpotMethod<OptimizedCallTarget.callRoot(Object[])>}
                    [thread:21] scope: TruffleCompilerThread-21.Truffle.TruffleGraal.GraalCompiler.GraalCompilerRoot.GraalCompiler.FrontEnd.HighTier.LoweringPhase.IncrementalCanonicalizerPhase.CanonicalizerPhase_Instance.InterceptException
                    Exception occurred in scope: TruffleCompilerThread-21.Truffle.TruffleGraal.GraalCompiler.GraalCompilerRoot.GraalCompiler.FrontEnd.HighTier.LoweringPhase.IncrementalCanonicalizerPhase.CanonicalizerPhase_Instance.InterceptException
                    Context obj java.lang.AssertionError
                    Context obj org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance@67e6dcb6
                    Context obj org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase@634d763b
                    Context obj org.graalvm.compiler.phases.common.LoweringPhase@4eaf3d72
                    Context obj org.graalvm.compiler.core.phases.HighTier@2e4ca0a4
                    Context obj StructuredGraph:4{Method RedBlackTree>>#treeAt:insert:	@14f01e19, HotSpotMethod<OptimizedCallTarget.callRoot(Object[])>}
                    Context obj jdk.vm.ci.hotspot.HotSpotCodeCacheProvider@776a87d1
                    Context obj Truffle<Method_RedBlackTree>>#treeAt:insert:	@14f01e19()>
[truffle] opt fail         Method RedBlackTree>>#treeAt:insert:	@14f01e19              |Reason java.lang.AssertionError 
java.lang.AssertionError
	at org.graalvm.compiler.core.common.type.IntegerStamp.createStamp(IntegerStamp.java:316)
	at org.graalvm.compiler.core.common.type.IntegerStamp.meet(IntegerStamp.java:334)
	at org.graalvm.compiler.nodes.type.StampTool.meetOrNull(StampTool.java:66)
	at org.graalvm.compiler.nodes.ValuePhiNode.inferStamp(ValuePhiNode.java:71)
	at org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.tryInferStamp(CanonicalizerPhase.java:431)
	at org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processNode(CanonicalizerPhase.java:259)
	at org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processWorkSet(CanonicalizerPhase.java:230)
	at org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.run(CanonicalizerPhase.java:200)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:47)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:203)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:40)
	at org.graalvm.compiler.phases.common.CanonicalizerPhase.applyIncremental(CanonicalizerPhase.java:152)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:58)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:36)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:203)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:134)
	at org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:248)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:241)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:86)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:203)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:134)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:179)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:203)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:134)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:231)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:174)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:160)
	at org.graalvm.compiler.truffle.TruffleCompiler.compileMethodHelper(TruffleCompiler.java:224)
	at org.graalvm.compiler.truffle.TruffleCompiler.compileMethod(TruffleCompiler.java:177)
	at org.graalvm.compiler.truffle.GraalTruffleRuntime.doCompile0(GraalTruffleRuntime.java:529)
	at org.graalvm.compiler.truffle.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:515)
	at org.graalvm.compiler.truffle.GraalTruffleRuntime$1.run(GraalTruffleRuntime.java:560)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.graalvm.compiler.core.CompilerThread.run(CompilerThread.java:51)
```

</details>

The full build server log is available here: https://gitlab.soft.vub.ac.be/stefan.marr/SOMns/builds/3115

To reproduce the problem, you can use the following steps:

```bash
git clone https://github.com/smarr/SOMns
cd SOMns
ant compile

export JVMCI_BIN=$YOUR_PATH_TO_YOUR_GRAAL_JVMCI_BINARY
export GRAAL_FLAGS=$ANY_GRAAL_FLAGS_PERHAPS
./som -t1  core-lib/Benchmarks/Harness.som CD  130 0 100
```

The CD benchmark fails, as well as the Vacation benchmark:
```bash
./som -t1  core-lib/Benchmarks/Harness.som Vacation  150 0 14
```

To determine the plain `java` command-line, use `-vv`:
```bash
./som -t1 -vv core-lib/Benchmarks/Harness.som CD  130 0 100
```

**Comment by smarr** [comment]
I did run a bisect and got the following result:

```
1d453dfc3b7df282a842e1cb01d14d52e9d6ba80 is the first bad commit
commit 1d453dfc3b7df282a842e1cb01d14d52e9d6ba80
Author: Gilles Duboscq <gilles.m.duboscq@oracle.com>
Date:   Fri Feb 24 17:41:18 2017 +0100

    Canonicalize NormalizeCompare patterns
```

@gilles-duboscq this seems to be the relevant change: https://github.com/graalvm/graal-core/commit/1d453dfc3b7df282a842e1cb01d14d52e9d6ba80

**Comment by tkrodriguez** [comment]
The problem is that NormalizeCompareNode produces ints but can be used to replace a long leading to the mismatch.  It's easy to fix.  I'll prepare a fix.

**Comment by tkrodriguez** [comment]
The fix for this in https://github.com/graalvm/graal/commit/eccbba1648856ee6f818bd0449880c298c3ccae0.  Note that all fixes going forward are in graal repo instead of graal-core.  You should be able to simply reset your remote to point at the new repo and pull that changes.  Or just blow away your old one an d fetch it.

**Comment by smarr** [comment]
@tkrodriguez thanks, the Vacation benchmark seems to be fixed by the change.
Can't verify CD yet, because there's a new issue: https://github.com/graalvm/graal/issues/217

**Comment by smarr** [comment]
Seems fixed. Thanks!
