### ISSUE TITLE
Gate task "CTW:hosted-product" fails with AssertionError: node is deleted!

### ISSUE THREAD

**Issue by sanzinger** [graalvm/graal-core#65]
Current revision of graal-core fails with the error below during mx gate. Tested on graal-core 01bf79766da8ac16ce569923cc7abe5b3f7a3ca9. 

@dougxc  provided a command to reproduce the issue: 

    mx --vm server ctw -esa -G:-InlineDuringParsing -G:-CompileTheWorldVerbose '-G:CompileTheWorldConfig=-Inline#+ExitVMOnException' '-G:CompileTheWorldExcludeMethodFilter=sun.awt.X11.*.*' '-G:CompileTheWorldMethodFilter=CDROutputStream_1_0.*'

<pre>CompileTheWorld : Waiting for 151938 compiles
[thread:92] scope: CompileTheWorld-92
  [thread:92] scope: CompileTheWorld-92.Compiling
    [thread:92] scope: CompileTheWorld-92.Compiling.GraalCompiler
      [thread:92] scope: CompileTheWorld-92.Compiling.GraalCompiler.FrontEnd
        [thread:92] scope: CompileTheWorld-92.Compiling.GraalCompiler.FrontEnd.MidTier
          [thread:92] scope: CompileTheWorld-92.Compiling.GraalCompiler.FrontEnd.MidTier.LoweringPhase
            [thread:92] scope: CompileTheWorld-92.Compiling.GraalCompiler.FrontEnd.MidTier.LoweringPhase.IncrementalCanonicalizerPhase
              [thread:92] scope: CompileTheWorld-92.Compiling.GraalCompiler.FrontEnd.MidTier.LoweringPhase.IncrementalCanonicalizerPhase.LoweringPhase_Round
                [thread:92] scope: CompileTheWorld-92.Compiling.GraalCompiler.FrontEnd.MidTier.LoweringPhase.IncrementalCanonicalizerPhase.LoweringPhase_Round.SchedulePhase
                  [thread:92] scope: CompileTheWorld-92.Compiling.GraalCompiler.FrontEnd.MidTier.LoweringPhase.IncrementalCanonicalizerPhase.LoweringPhase_Round.SchedulePhase.InterceptException
                  Exception occurred in scope: CompileTheWorld-92.Compiling.GraalCompiler.FrontEnd.MidTier.LoweringPhase.IncrementalCanonicalizerPhase.LoweringPhase_Round.SchedulePhase.InterceptException
                  Context obj java.lang.AssertionError: node is deleted!
                  Context obj com.oracle.graal.phases.schedule.SchedulePhase@750ccbef
                  Context obj com.oracle.graal.phases.common.LoweringPhase$Round@40aa66b8
                  Context obj com.oracle.graal.phases.common.IncrementalCanonicalizerPhase@796fa0f
                  Context obj com.oracle.graal.phases.common.LoweringPhase@2ec92d0e
                  Context obj com.oracle.graal.compiler.phases.MidTier@3d09d88b
                  Context obj StructuredGraph:8101{HotSpotMethod<CDROutputStream_1_0.write_abstract_interface(Object)>}
                  Context obj jdk.vm.ci.hotspot.HotSpotCodeCacheProvider@1ef32769
                  Context obj DebugDumpScope[9430]
java.lang.AssertionError: node is deleted!
        at com.oracle.graal.graph.NodeBitMap.check(NodeBitMap.java:156)
        at com.oracle.graal.graph.NodeBitMap.isMarked(NodeBitMap.java:67)
        at com.oracle.graal.graph.NodeBitMap.checkAndMarkInc(NodeBitMap.java:73)
        at com.oracle.graal.phases.schedule.SchedulePhase$Instance.processStack(SchedulePhase.java:700)
        at com.oracle.graal.phases.schedule.SchedulePhase$Instance.scheduleEarliestIterative(SchedulePhase.java:562)
        at com.oracle.graal.phases.schedule.SchedulePhase$Instance.run(SchedulePhase.java:149)
        at com.oracle.graal.phases.schedule.SchedulePhase.run(SchedulePhase.java:125)
        at com.oracle.graal.phases.Phase.run(Phase.java:51)
        at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:146)
        at com.oracle.graal.phases.Phase.apply(Phase.java:44)
        at com.oracle.graal.phases.common.LoweringPhase$Round.run(LoweringPhase.java:307)
        at com.oracle.graal.phases.Phase.run(Phase.java:51)
        at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:146)
        at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:136)
        at com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:116)
        at com.oracle.graal.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:54)
        at com.oracle.graal.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:36)
        at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:146)
        at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:136)
        at com.oracle.graal.phases.common.LoweringPhase.lower(LoweringPhase.java:229)
        at com.oracle.graal.phases.common.LoweringPhase.checkPostLowering(LoweringPhase.java:214)
        at com.oracle.graal.phases.common.LoweringPhase.run(LoweringPhase.java:223)
        at com.oracle.graal.phases.common.LoweringPhase.run(LoweringPhase.java:81)
        at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:146)
        at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:136)
        at com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:116)
        at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:146)
        at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:136)
        at com.oracle.graal.compiler.GraalCompiler.emitFrontEnd(GraalCompiler.java:201)
</pre>

**Comment by tkrodriguez** [comment]
This is a bug in the ShortCicuitOr IfNode changes with conditions with multiple users.  I've got a fix but I'm want to write a couple unit tests first.

**Comment by tkrodriguez** [comment]
I've disabled the ShortCircuitOrNode until I get a unit test for it together.  The amd64 post gate is clean as of #66 and the sparc one is waiting for #64.

**Comment by sanzinger** [comment]
I have run a successful gate on SPARC with rev. 7ac09b8
